### ISSUE TITLE
null pointer exception due to .getVoxelDimensions() ?

### ISSUE THREAD

**Issue by NicoKiaru** [saalfeldlab/bigwarp#101]
Hi!

I get this error with 2d sources when initializing BigWarp in bdv-playground

```
java.lang.NullPointerException
	at bigwarp.source.WarpMagnitudeSource.<init>(WarpMagnitudeSource.java:54)
	at bigwarp.BigWarp.addWarpMagnitudeSource(BigWarp.java:2134)
	at bigwarp.BigWarp.<init>(BigWarp.java:365)

```
Maybe it also occurs with 3d, I need to check

I think it's the getVoxelDimensions which could return null.

https://github.com/saalfeldlab/bigwarp/blob/fd3531fc29118e4763bb34de39ed8be7ea07841f/src/main/java/bigwarp/source/WarpMagnitudeSource.java#L54

My dependency is `<bigwarp_fiji.version>6.0.2</bigwarp_fiji.version>`

Let me know if I can help

**Comment by bogovicj** [comment]
Will check it out, thanks for reporting!

**Comment by bogovicj** [comment]
The above commit should fix this, but I'll leave this issue open for a bit.
Thanks as always @NicoKiaru !

**Comment by NicoKiaru** [comment]
Perfect, it works! Thanks @bogovicj !

FYI, I still do not understand why I had these non defined `VoxelDimensions`...
